# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
