# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 21:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locX', models.FloatField()),
                ('locY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CatScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='CSP',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('codename', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('opPositive', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('opNeutral', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('opNegative', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avgRating', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='CSPLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locX', models.FloatField()),
                ('locY', models.FloatField()),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
            ],
        ),
        migrations.CreateModel(
            name='CtrlGrpWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrlGroup', models.CharField(max_length=3)),
                ('domain', models.CharField(max_length=8)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=12)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('source', models.CharField(max_length=100, null=True)),
                ('dateMade', models.DateField(null=True)),
                ('locMade', models.CharField(max_length=100, null=True)),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNum', models.IntegerField(null=True, unique=True)),
                ('plaintext', models.CharField(max_length=20000, null=True)),
                ('source', models.CharField(max_length=100, null=True)),
                ('dateMade', models.DateField(null=True)),
                ('locMade', models.CharField(max_length=100, null=True)),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
            ],
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ctrlgrpweight',
            unique_together=set([('ctrlGroup', 'domain')]),
        ),
        migrations.AddField(
            model_name='catscore',
            name='CSP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP'),
        ),
        migrations.AddField(
            model_name='app',
            name='currCSP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP'),
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='catscore',
            unique_together=set([('CSP', 'type')]),
        ),
    ]
