# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 22:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocX', models.FloatField()),
                ('LocY', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CSP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fDowntime', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('uDowntime', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('redundVal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='CSPLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocX', models.FloatField()),
                ('LocY', models.FloatField()),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('source', models.CharField(max_length=100)),
                ('dateMade', models.DateField()),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaintext', models.CharField(max_length=2000)),
                ('dateMade', models.DateField()),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='currCSP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP'),
        ),
        migrations.AddField(
            model_name='app',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
