# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 19:57
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CSPtool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('CSP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSPtool.CSP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='app',
            old_name='LocX',
            new_name='locX',
        ),
        migrations.RenameField(
            model_name='app',
            old_name='LocY',
            new_name='locY',
        ),
        migrations.RenameField(
            model_name='csploc',
            old_name='LocX',
            new_name='locX',
        ),
        migrations.RenameField(
            model_name='csploc',
            old_name='LocY',
            new_name='locY',
        ),
    ]
