# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0002_auto_20170619_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='dateMade',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='dateMade',
            field=models.DateField(null=True),
        ),
    ]
