# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0004_auto_20170622_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='plaintext',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
