# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0005_auto_20170622_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csp',
            name='fDowntime',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='csp',
            name='redundVal',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='csp',
            name='uDowntime',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
