# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0006_auto_20170626_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='locMade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('dateMade', 'locMade')]),
        ),
    ]
