# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0007_auto_20170626_1604'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('CSP', 'dateMade', 'locMade')]),
        ),
    ]
