# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0011_auto_20170627_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csp',
            name='fDowntime',
        ),
        migrations.RemoveField(
            model_name='csp',
            name='redundVal',
        ),
        migrations.RemoveField(
            model_name='csp',
            name='uDowntime',
        ),
        migrations.AddField(
            model_name='csp',
            name='opNegative',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='csp',
            name='opNeutral',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='csp',
            name='opPositive',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
