# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0012_auto_20170706_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='idNum',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
