# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0013_auto_20170706_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='csp',
            name='avgRating',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
