# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSPtool', '0016_catscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='csp',
            name='codename',
            field=models.CharField(default='Tempname', max_length=40),
            preserve_default=False,
        ),
    ]
